99_唐华_第二次课程作业
Guigulive/Team-J pull request #25
Opened 2018-03-17 10:18 UTC by tanghuajy

2018-03-17 16:30 UTC, old2 requested changes

2018-03-17 16:30 UTC, old2 commented on Lesson-2/assignment/99_唐华_第二课作业
> +第二步：
优化时未考虑 updateEmployee

2018-03-17 16:30 UTC, old2 commented on Lesson-2/assignment/99_唐华_第二课作业
> +每次添加或移除员工的时候，直接计算totalSalary，避免再次遍历数组重复计算消耗gas。
优化后的gas消耗是多少？

2018-03-18 12:03 UTC, tanghuajy commented on Lesson-2/assignment/99_唐华_第二课作业
> +第二步：
updateEmployee中增加totalSalary += employees[index].salary;

2018-03-18 12:04 UTC, tanghuajy commented on Lesson-2/assignment/99_唐华_第二课作业
> +每次添加或移除员工的时候，直接计算totalSalary，避免再次遍历数组重复计算消耗gas。
优化后，calculateRunway（）的gas消耗不变，为22124+852，addEmployee（）和calculateRunway（）的整体gas消耗小于优化之前。

2018-03-20 03:15 UTC, merged