唐华-99-第一次作业
Guigulive/Team-J pull request #5
Opened 2018-03-13 11:55 UTC by tanghuajy

2018-03-13 12:50 UTC, tanghuajy commented
第一次作业

2018-03-14 17:30 UTC, old2 requested changes

2018-03-14 17:30 UTC, old2 commented on Lesson-1/assignment/99_唐华_第一课作业
> +    function setEmployeeSalary(uint x) constant returns (uint){
需要判断调用者身份  还有 工资单位没有设置

2018-03-14 17:30 UTC, old2 commented on Lesson-1/assignment/99_唐华_第一课作业
> +    function setEmployeeAddress(address y) constant returns (address){
判断调用者身份

2018-03-14 17:30 UTC, old2 commented on Lesson-1/assignment/99_唐华_第一课作业
> +    address employee = 0x0;
初始化设置成0 等于没有初始化

2018-03-15 13:52 UTC, old2 approved these changes

2018-03-15 13:53 UTC, merged