96_徐臻_第一次作业
Guigulive/Team-J pull request #8
Opened 2018-03-13 19:32 UTC by larryxuzhen

2018-03-14 17:19 UTC, old2 commented on hw-class1-larryxuzhen.sol
> +    //change the address of employee, this employee can do it
这里的用意是让雇主更改雇员，需要对前一任雇员工资进行结算。不是让雇员自己更换收钱的地址

2018-03-14 17:19 UTC, old2 requested changes

2018-03-14 17:19 UTC, old2 commented on hw-class1-larryxuzhen.sol
> +    //initialize the employee's address, the owner can do it
这里的用意是让雇主更改雇员，需要对前一任雇员工资进行结算。不是让雇员自己更换收钱的地址

2018-03-15 13:10 UTC, larryxuzhen commented on hw-class1-larryxuzhen.sol
> +    //initialize the employee's address, the owner can do it
之前理解错了，以为是员工自己想换另一个钱包。。更新了下，老师看看行不~

2018-03-15 13:54 UTC, merged